### -----------------------------------------------------------
### This init macro simulates Tl decays in the EP.
### -----------------------------------------------------------

##### GENERATOR #####
/Generator/IonGenerator/atomic_number 81
/Generator/IonGenerator/mass_number 208
#/Generator/IonGenerator/region STEEL_PLATE
/Generator/IonGenerator/region Cu_PLATE

/Geometry/EPrejfac/steel_length 0. cm
/Geometry/EPrejfac/specific_vertex  0 0 -100 cm

/Actions/DefaultEventAction/min_energy 2.3 MeV
#/Actions/SaveAllSteppingAction/select_particle e-
#/Actions/SaveAllSteppingAction/select_particle gamma
#/Actions/SaveAllSteppingAction/select_volume XENON_GAS

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile EP_plates.next
