### -----------------------------------------------------------
### This init macro simulates Tl disintegrations in the EP.
### -----------------------------------------------------------

#/Generator/LambertianGenerator/particle geantino
#/Generator/LambertianGenerator/min_energy 2.9 eV
#/Generator/LambertianGenerator/max_energy 2.9 eV
#/Generator/LambertianGenerator/region AD_HOC
#/Generator/LambertianGenerator/momentum 0 0 1
#/Generator/LambertianGenerator/min_costheta 0.9935
#/Generator/LambertianGenerator/max_costheta 1.
#/Generator/LambertianGenerator/region STEEL_PLATE

##### GENERATOR #####
#/Generator/IonGenerator/atomic_number 81
#/Generator/IonGenerator/mass_number 208
#/Generator/IonGenerator/region STEEL_PLATE

#prueba 0nu
/Generator/Decay0Interface/region Cu_PLATE
/Generator/Decay0Interface/inputFile /Users/miryam/Developments/NEXT/federica/generation_test_2.txt

/Geometry/EPrejfac/steel_length 0. cm
/Geometry/EPrejfac/specific_vertex  0 0 -100 cm

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile EP_plates.next
